---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    fluxcd.io/tag.chart-image: semver:~4.0
    fluxcd.io/locked: 'true'
    fluxcd.io/locked_user: Raffael Sahli <raffael.sahli@doodle.com>
spec:
  releaseName: mongodb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: mongodb
    version: 7.6.3
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.14
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 1000
      runAsUser: 1000
